CREATE DATABASE JogoMemoria;
USE JogoMemoria;

CREATE TABLE jogador(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tempo INT
);

SELECT * FROM jogador ORDER BY tempo ASC;